apiVersion: apps/v1
kind: Deployment
metadata:
  name: stomp-listener
  labels:
    app: stomp-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stomp-listener
  template:
    metadata:
      labels:
        app: stomp-listener
    spec:
      containers:
        - name: stomp-listener
          image: dkoun/stomp-listener:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: EMS_HOST
              value: "emsserver-ems-server"
            - name: EMS_PORT
              value: "61610"
            # add any other env vars your listener.py needs
